version: "3.1"
services:
  db:
    image: postgres
    container_name: my-bank-db
    restart: always
    environment:
      POSTGRES_DB: my-bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 315221
    ports:
      - "5432:5432"

## CONFIG TESTE PARA CRIAR DB E CONEXÃO COM PostgREST
# version: '3'
# services:
#   server:
#     image: postgrest/postgrest
#     ports:
#       - "3050:3050"
#     environment:
#       # POSTGRES_DB: my-bank
#       PGRST_DB_URI: postgres://postgres:315221@db:5432/my-bank
#       PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3050
#     depends_on:
#       - db
#   db:
#     image: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: my-bank
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 315221